set-option -g prefix C-o
bind-key C-w last-window # 方便切换，个人习惯
bind-key a send-prefix
# shell下的Ctrl+a切换到行首在此配置下失效，此处设置之后Ctrl+a再按a即可切换至shell行首

# reload settings # 重新读取加载配置文件
bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Ctrl-Left/Right cycles thru windows (no prefix)
# 不使用prefix键，使用Ctrl和左右方向键方便切换窗口
bind-key -n M-k select-pane -U
bind-key -n M-j select-pane -D
bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
bind-key -n M-z resize-pane -Z
bind-key h split-window -h
bind-key v split-window -v
bind-key -n M-q select-layout tiled
# displays
bind-key * list-clients

set -g default-terminal screen-256color
set-option -ga terminal-overrides ",*256col*:Tc" # 这句是关键

set -g display-time 5000                    # status line messages display
# set -g status-utf8 on                       # enable utf-8
set -g history-limit 100000                 # scrollback buffer n lines
# setw -g mode-keys vi                        # use vi mode

# start window indexing at one instead of zero 使窗口从1开始，默认从0开始
set -g base-index 1
setenv -g SSH_AUTH_SOCK $HOME/.ssh_real

set -g default-shell /bin/zsh
set -g default-command /bin/zsh
